import { auditLog, db, entities, itilActors, queuedNotifications, recurringTicketTemplates, tickets, users, type Entity, type User } from "@itsm/db";
import { eq, inArray, like } from "drizzle-orm";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createEntity } from "../entities/entity-service";
import { createUser } from "../users/user-service";
import {
  createRecurringTicketTemplate,
  listRecurringTicketTemplates,
  runRecurringTicketsSweep,
} from "./recurring-ticket-service";

const PREFIX = "__vitest_itil__recurring_ticket";

let entity: Entity;
let requester: User;
const templateIds: string[] = [];

beforeAll(async () => {
  entity = await createEntity({ name: `${PREFIX}_entity_${Date.now()}` });
  requester = await createUser({
    email: `${PREFIX}_${Date.now()}@example.test`,
    username: `${PREFIX}_${Date.now()}`,
    password: "not-used-in-tests",
    displayName: `${PREFIX} requester`,
  });
});

afterAll(async () => {
  // Tickets generated by the sweep are identified by their title (titleTemplate carries our
  // PREFIX), not tracked by id up front, since createTicket() (called internally by the sweep)
  // returns void from this file's perspective.
  const generated = await db.select({ id: tickets.id }).from(tickets).where(like(tickets.title, `${PREFIX}%`));
  const generatedIds = generated.map((t) => t.id);

  if (generatedIds.length > 0) {
    await db.delete(itilActors).where(inArray(itilActors.itilId, generatedIds));
  }
  await db.delete(queuedNotifications).where(eq(queuedNotifications.recipientUserId, requester.id));
  await db.delete(auditLog).where(eq(auditLog.entityId, entity.id));
  if (generatedIds.length > 0) {
    await db.delete(tickets).where(inArray(tickets.id, generatedIds));
  }
  if (templateIds.length > 0) {
    await db.delete(recurringTicketTemplates).where(inArray(recurringTicketTemplates.id, templateIds));
  }
  await db.delete(entities).where(eq(entities.id, entity.id));
  await db.delete(users).where(eq(users.id, requester.id));
});

describe("recurring-ticket-service", () => {
  it("creates a template with nextRunAt scheduled intervalMinutes from now", async () => {
    const before = Date.now();
    const template = await createRecurringTicketTemplate({
      entityId: entity.id,
      name: `${PREFIX} weekly backup check`,
      titleTemplate: `${PREFIX} Revisar backup semanal`,
      contentTemplate: "Verificar que el backup semanal se haya ejecutado correctamente.",
      requesterUserId: requester.id,
      intervalMinutes: 60,
    });
    templateIds.push(template.id);

    expect(template.isActive).toBe(true);
    expect(template.ticketType).toBe("request");

    const expectedNextRunAt = before + 60 * 60_000;
    expect(Math.abs(template.nextRunAt.getTime() - expectedNextRunAt)).toBeLessThan(5000);
  });

  it("listRecurringTicketTemplates returns active templates scoped to the entity", async () => {
    const template = await createRecurringTicketTemplate({
      entityId: entity.id,
      name: `${PREFIX} list check`,
      titleTemplate: `${PREFIX} list check ticket`,
      contentTemplate: "content",
      requesterUserId: requester.id,
      intervalMinutes: 30,
    });
    templateIds.push(template.id);

    const listed = await listRecurringTicketTemplates(entity.id);
    expect(listed.map((t) => t.id)).toContain(template.id);
  });

  it("a due template fires a real ticket via the sweep and reschedules nextRunAt forward", async () => {
    const template = await createRecurringTicketTemplate({
      entityId: entity.id,
      name: `${PREFIX} due template`,
      titleTemplate: `${PREFIX} Ticket generado por regla recurrente`,
      contentTemplate: "Contenido generado automaticamente.",
      requesterUserId: requester.id,
      intervalMinutes: 45,
    });
    templateIds.push(template.id);

    // createRecurringTicketTemplate always schedules nextRunAt in the future - force it into the
    // past here to simulate "due now" the way apps/worker's scheduled sweep would eventually see it.
    const forcedPast = new Date(Date.now() - 60_000);
    await db.update(recurringTicketTemplates).set({ nextRunAt: forcedPast }).where(eq(recurringTicketTemplates.id, template.id));

    // runRecurringTicketsSweep() scans every due template system-wide, not just ours, so assert
    // on our own template/ticket rather than the global returned count.
    await runRecurringTicketsSweep();

    const generatedTickets = await db.select().from(tickets).where(eq(tickets.title, template.titleTemplate));
    expect(generatedTickets).toHaveLength(1);
    expect(generatedTickets[0]?.content).toBe(template.contentTemplate);
    expect(generatedTickets[0]?.entityId).toBe(entity.id);

    const [reloadedTemplate] = await db.select().from(recurringTicketTemplates).where(eq(recurringTicketTemplates.id, template.id));
    expect(reloadedTemplate?.nextRunAt.getTime()).toBeGreaterThan(forcedPast.getTime());
    // Rescheduled ~45 minutes ahead of the sweep's "now", not the original due time.
    expect(reloadedTemplate?.nextRunAt.getTime()).toBeGreaterThan(Date.now() + 40 * 60_000);
  });

  it("a template that isn't due yet is left untouched by the sweep", async () => {
    const template = await createRecurringTicketTemplate({
      entityId: entity.id,
      name: `${PREFIX} not due`,
      titleTemplate: `${PREFIX} Ticket que no deberia generarse todavia`,
      contentTemplate: "content",
      requesterUserId: requester.id,
      intervalMinutes: 120,
    });
    templateIds.push(template.id);

    await runRecurringTicketsSweep();

    const generatedTickets = await db.select().from(tickets).where(eq(tickets.title, template.titleTemplate));
    expect(generatedTickets).toHaveLength(0);
  });
});
