CREATE INDEX "groups_entity_idx" ON "groups" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "groups_parent_idx" ON "groups" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "user_groups_group_idx" ON "user_groups" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "user_profiles_user_idx" ON "user_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_profiles_profile_idx" ON "user_profiles" USING btree ("profile_id");--> statement-breakpoint
CREATE INDEX "audit_log_entity_idx" ON "audit_log" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "dropdown_items_entity_idx" ON "dropdown_items" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "software_entity_idx" ON "software" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "software_licenses_entity_idx" ON "software_licenses" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "software_licenses_software_idx" ON "software_licenses" USING btree ("software_id");--> statement-breakpoint
CREATE INDEX "tickets_entity_idx" ON "tickets" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "problems_entity_idx" ON "problems" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "changes_entity_idx" ON "changes" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "sla_policies_entity_idx" ON "sla_policies" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "queued_notifications_recipient_idx" ON "queued_notifications" USING btree ("recipient_user_id");--> statement-breakpoint
CREATE INDEX "recurring_ticket_templates_entity_idx" ON "recurring_ticket_templates" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "suppliers_entity_idx" ON "suppliers" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "contacts_entity_idx" ON "contacts" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "budgets_entity_idx" ON "budgets" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "contracts_entity_idx" ON "contracts" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "certificates_entity_idx" ON "certificates" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "certificates_assigned_asset_idx" ON "certificates" USING btree ("assigned_asset_id");--> statement-breakpoint
CREATE INDEX "kb_article_comments_article_idx" ON "kb_article_comments" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "kb_articles_entity_idx" ON "kb_articles" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "project_costs_project_idx" ON "project_costs" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "project_tasks_project_idx" ON "project_tasks" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "projects_entity_idx" ON "projects" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "saved_searches_entity_idx" ON "saved_searches" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "rss_feed_cached_items_feed_idx" ON "rss_feed_cached_items" USING btree ("feed_id");--> statement-breakpoint
CREATE INDEX "rule_actions_rule_idx" ON "rule_actions" USING btree ("rule_id");--> statement-breakpoint
CREATE INDEX "rule_criteria_rule_idx" ON "rule_criteria" USING btree ("rule_id");--> statement-breakpoint
CREATE INDEX "rules_entity_idx" ON "rules" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "inventory_agents_entity_idx" ON "inventory_agents" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "inventory_submissions_agent_idx" ON "inventory_submissions" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX "impact_relations_impacted_idx" ON "impact_relations" USING btree ("impacted_asset_id");--> statement-breakpoint
CREATE INDEX "documents_entity_idx" ON "documents" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "consumable_items_entity_idx" ON "consumable_items" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "consumables_item_idx" ON "consumables" USING btree ("consumable_item_id");--> statement-breakpoint
CREATE INDEX "consumables_assigned_asset_idx" ON "consumables" USING btree ("assigned_asset_id");--> statement-breakpoint
CREATE INDEX "service_catalog_items_entity_idx" ON "service_catalog_items" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "reminders_entity_idx" ON "reminders" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "reminders_owner_idx" ON "reminders" USING btree ("owner_user_id");