CREATE INDEX "entities_parent_idx" ON "entities" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "users_default_entity_idx" ON "users" USING btree ("default_entity_id");--> statement-breakpoint
CREATE INDEX "accounts_user_idx" ON "accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_user_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_profiles_entity_idx" ON "user_profiles" USING btree ("entity_id");--> statement-breakpoint
CREATE INDEX "audit_log_actor_idx" ON "audit_log" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "dropdown_items_parent_idx" ON "dropdown_items" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "asset_field_definitions_dropdown_category_idx" ON "asset_field_definitions" USING btree ("dropdown_category_id");--> statement-breakpoint
CREATE INDEX "assets_status_dropdown_item_idx" ON "assets" USING btree ("status_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "assets_manufacturer_dropdown_item_idx" ON "assets" USING btree ("manufacturer_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "assets_model_dropdown_item_idx" ON "assets" USING btree ("model_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "assets_location_dropdown_item_idx" ON "assets" USING btree ("location_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "assets_user_idx" ON "assets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "assets_group_idx" ON "assets" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "computers_os_dropdown_item_idx" ON "computers" USING btree ("os_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "computers_os_version_dropdown_item_idx" ON "computers" USING btree ("os_version_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "network_equipment_device_type_dropdown_item_idx" ON "network_equipment" USING btree ("device_type_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "asset_software_installations_software_version_idx" ON "asset_software_installations" USING btree ("software_version_id");--> statement-breakpoint
CREATE INDEX "asset_software_installations_software_license_idx" ON "asset_software_installations" USING btree ("software_license_id");--> statement-breakpoint
CREATE INDEX "software_manufacturer_dropdown_item_idx" ON "software" USING btree ("manufacturer_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "software_category_dropdown_item_idx" ON "software" USING btree ("category_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "software_licenses_software_version_idx" ON "software_licenses" USING btree ("software_version_id");--> statement-breakpoint
CREATE INDEX "software_versions_os_dropdown_item_idx" ON "software_versions" USING btree ("os_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "itil_costs_budget_idx" ON "itil_costs" USING btree ("budget_id");--> statement-breakpoint
CREATE INDEX "itil_timeline_items_created_by_idx" ON "itil_timeline_items" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "tickets_category_dropdown_item_idx" ON "tickets" USING btree ("category_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "problems_category_dropdown_item_idx" ON "problems" USING btree ("category_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "changes_category_dropdown_item_idx" ON "changes" USING btree ("category_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "itil_sla_assignments_sla_policy_idx" ON "itil_sla_assignments" USING btree ("sla_policy_id");--> statement-breakpoint
CREATE INDEX "queued_notifications_template_key_idx" ON "queued_notifications" USING btree ("template_key");--> statement-breakpoint
CREATE INDEX "recurring_ticket_templates_requester_idx" ON "recurring_ticket_templates" USING btree ("requester_user_id");--> statement-breakpoint
CREATE INDEX "contacts_supplier_idx" ON "contacts" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "contract_assets_asset_idx" ON "contract_assets" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "contracts_supplier_idx" ON "contracts" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "kb_article_categories_category_idx" ON "kb_article_categories" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "kb_article_comments_author_idx" ON "kb_article_comments" USING btree ("author_user_id");--> statement-breakpoint
CREATE INDEX "kb_article_comments_parent_idx" ON "kb_article_comments" USING btree ("parent_comment_id");--> statement-breakpoint
CREATE INDEX "kb_articles_author_idx" ON "kb_articles" USING btree ("author_user_id");--> statement-breakpoint
CREATE INDEX "kb_categories_parent_idx" ON "kb_categories" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "reservations_requested_by_idx" ON "reservations" USING btree ("requested_by_user_id");--> statement-breakpoint
CREATE INDEX "project_costs_budget_idx" ON "project_costs" USING btree ("budget_id");--> statement-breakpoint
CREATE INDEX "project_tasks_parent_task_idx" ON "project_tasks" USING btree ("parent_task_id");--> statement-breakpoint
CREATE INDEX "project_tasks_project_task_state_dropdown_item_idx" ON "project_tasks" USING btree ("project_task_state_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "projects_parent_project_idx" ON "projects" USING btree ("parent_project_id");--> statement-breakpoint
CREATE INDEX "projects_project_state_dropdown_item_idx" ON "projects" USING btree ("project_state_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "projects_project_type_dropdown_item_idx" ON "projects" USING btree ("project_type_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "projects_manager_idx" ON "projects" USING btree ("manager_user_id");--> statement-breakpoint
CREATE INDEX "projects_group_idx" ON "projects" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "saved_search_alerts_saved_search_idx" ON "saved_search_alerts" USING btree ("saved_search_id");--> statement-breakpoint
CREATE INDEX "saved_searches_owner_idx" ON "saved_searches" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "rss_feeds_owner_idx" ON "rss_feeds" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "dashboard_cards_dashboard_idx" ON "dashboard_cards" USING btree ("dashboard_id");--> statement-breakpoint
CREATE INDEX "dashboards_owner_idx" ON "dashboards" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "inventory_agents_asset_idx" ON "inventory_agents" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "cables_endpoint_a_asset_idx" ON "cables" USING btree ("endpoint_a_asset_id");--> statement-breakpoint
CREATE INDEX "cables_endpoint_b_asset_idx" ON "cables" USING btree ("endpoint_b_asset_id");--> statement-breakpoint
CREATE INDEX "cables_cable_type_dropdown_item_idx" ON "cables" USING btree ("cable_type_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "cluster_members_member_asset_idx" ON "cluster_members" USING btree ("member_asset_id");--> statement-breakpoint
CREATE INDEX "enclosure_slots_enclosure_asset_idx" ON "enclosure_slots" USING btree ("enclosure_asset_id");--> statement-breakpoint
CREATE INDEX "enclosure_slots_occupant_asset_idx" ON "enclosure_slots" USING btree ("occupant_asset_id");--> statement-breakpoint
CREATE INDEX "rack_slots_occupant_asset_idx" ON "rack_slots" USING btree ("occupant_asset_id");--> statement-breakpoint
CREATE INDEX "document_items_document_idx" ON "document_items" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "documents_uploaded_by_idx" ON "documents" USING btree ("uploaded_by_user_id");--> statement-breakpoint
CREATE INDEX "consumable_items_supplier_idx" ON "consumable_items" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "service_catalog_items_category_dropdown_item_idx" ON "service_catalog_items" USING btree ("category_dropdown_item_id");--> statement-breakpoint
CREATE INDEX "ticket_field_definitions_dropdown_category_idx" ON "ticket_field_definitions" USING btree ("dropdown_category_id");